import CppSrc from "./c++.svg";
import CssSrc from "./css.svg";
import DockerSrc from "./docker.svg";
import GitHubSrc from "./github.svg";
import GitlabSrc from "./gitlab.svg";
import GoogleCloudSrc from "./google-cloud.svg";
import HtmlSrc from "./html.svg";
import JavascriptSrc from "./javascript.svg";
import KubernetesSrc from "./kubernetes.svg";
import MobxSrc from "./mobx.svg";
import MongodbSrc from "./mongodb.svg";
import NodejsSrc from "./nodejs.svg";
import PhpSrc from "./php.svg";
import PostgresqlSrc from "./postgresql.svg";
import PrometheusSrc from "./prometheus.svg";
import PythonSrc from "./python.svg";
import ReactNativeSrc from "./react-native.svg";
import ReactSrc from "./react.svg";
import RedisSrc from "./redis.svg";
import SassSrc from "./sass.svg";
import SoliditySrc from "./solidity.svg";
import TypescriptSrc from "./typescript.svg";
import WebpackSrc from "./webpack.svg";

export const CppIcon = () => <img src={CppSrc} alt="C++ Logo"/>;
export const CssIcon = () => <img src={CssSrc} alt="CSS Logo"/>;
export const DockerIcon = () => <img src={DockerSrc} alt="Docker Logo"/>;
export const GitlabIcon = () => <img src={GitlabSrc} alt="Gitlab Logo"/>;
export const HtmlIcon = () => <img src={HtmlSrc} alt="HTML Logo"/>;
export const JavascriptIcon = () => <img src={JavascriptSrc} alt="Javascript Logo"/>;
export const KubernetesIcon = () => <img src={KubernetesSrc} alt="Kubernetes Logo"/>;
export const MongodbIcon = () => <img src={MongodbSrc} alt="MongoDB Logo"/>;
export const NodejsIcon = () => <img src={NodejsSrc} alt="NodeJS Logo"/>;
export const PostgresqlIcon = () => <img src={PostgresqlSrc} alt="PostgreSQL Logo"/>;
export const PrometheusIcon = () => <img src={PrometheusSrc} alt="Prometheus Logo"/>;
export const PythonIcon = () => <img src={PythonSrc} alt="Python Logo"/>;
export const ReactIcon = () => <img src={ReactSrc} alt="React Logo"/>;
export const ReactNativeIcon = () => <img src={ReactNativeSrc} alt="React Native Logo"/>;
export const SassIcon = () => <img src={SassSrc} alt="Sass Logo"/>;
export const SolidityIcon = () => <img src={SoliditySrc} alt="Solidity Logo"/>;
export const TypescriptIcon = () => <img src={TypescriptSrc} alt="Typescript Logo"/>;
export const WebpackIcon = () => <img src={WebpackSrc} alt="Webpack Logo"/>;
export const MobxIcon = () => <img src={MobxSrc} alt="Mobx Logo"/>;
export const PhpIcon = () => <img src={PhpSrc} alt="PHP Logo"/>;
export const RedisIcon = () => <img src={RedisSrc} alt="Redis Logo"/>;
export const GithubIcon = () => <img src={GitHubSrc} alt="Github Logo"/>;
export const GoogleCloudIcon = () => <img src={GoogleCloudSrc} alt="Google Cloud Logo"/>;

// typescript declare for svg import
declare module "*.svg";